### ISSUE TITLE
Theme choice

### ISSUE THREAD

**Issue by willgeiken** [adrimcdo/issues-lab-week9#3]
I don't actually know what this theme looks like, but I'm going to pretend that I don't like it and suggest you consider an alternate theme. Please feel free to ignore!

https://github.com/adrimcdo/issues-lab-week9/blob/2367e20cb5aef087226915c9707d60acb6221b2d/got_issues.Rmd#L37

**Comment by adrimcdo** [comment]
updated theme choice!
